apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-deployment
  labels:
    app: tasky
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      serviceAccountName: webapp-sa #Service Account
      containers:
      - name: tasky
        image: droog72/tasky:1.1
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: dbconnect
              key: mongodb_uri
        ports:
        - containerPort: 8080
